1. Buatlah Tensor di bawah ini dengan Python:

In [1]:
import numpy as np

#Membuat Tensor
Tensor = np.array(
    [
     [[23, 50], [7, 12]], [[57, 67], [99, 43]],
     [[75, 21], [57, 12]], [[87, 26], [18, 84]]
    ]
)

Tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

2. Lakukan perkalian terhadap matrix berikut

In [4]:
A = np.array([[23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]])

B = np.array([17, 22, 19])
print(A.shape)
print(B.shape)

# Perkalian Matrix
print(A.dot(B))

(3, 3)
(3,)
[1852 2454 4305]


3. Lakukan Transpose, hitung determinan, dan inverse
terhadap matrix dibawah ini: 

In [5]:
A = np.array([[23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]])

In [6]:
# Transpose
print(A.T)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [8]:
# determinan

print(np.linalg.det(A))

131344.0000000002


In [9]:
# Inverse

print(np.linalg.inv(A))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
