1. Apakah x adalah eigenvector dari A?
Jika Iya, berapakah eigenvalue-nya?

In [1]:
 import numpy as np

 x = np.array([1, 3])
 A = np.array([[1, -1], [6, 4]]) 

In [3]:
print(x)
print('-'*100)
print(A)

[1 3]
----------------------------------------------------------------------------------------------------
[[ 1 -1]
 [ 6  4]]


In [6]:
from numpy.linalg import eig

In [8]:
eigVal, eigVec = eig(A)

In [9]:
eigVal

array([2.5+1.93649167j, 2.5-1.93649167j])

In [10]:
eigVec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [12]:
np.allclose(x, eigVec[0])

False

In [13]:
np.allclose(x, eigVec[1])

False

Dapat disimpulkan bahwa x bukan EigenVector dari A